In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df=pd.read_csv('train.txt',sep=';',header = None,names =['text','emotion'])
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [8]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [9]:
df['emotion'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [10]:
unique_emotions=df['emotion'].unique()
emotion_number= {}
i=0
for emo in unique_emotions:
    emotion_number[emo]=i
    i+=1
df['emotion']= df['emotion'].map(emotion_number)
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [11]:
df['text']=df['text'].apply(lambda x : x.lower())

In [12]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

df['text']=df['text'].apply(remove_punc)

In [13]:
def remove_numbers(txt):
  new=""
  for i in txt:
    if not i.isdigit():
      new=new+i
  return new

df['text']=df['text'].apply(remove_numbers)

In [14]:
import re

def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)
df['text']=df['text'].apply(remove_urls)

In [15]:
def remove_emojis(txt):
  new=""
  for i in txt:
    if i.isascii():
      new+=i
  return new

df['text']=df['text'].apply(remove_emojis)

In [16]:
import nltk

In [17]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [18]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [19]:
stopwords= set(stopwords.words('english'))
stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [20]:
len(stopwords)

198

In [21]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [22]:
def remove(txt):
  words= word_tokenize(txt)
  cleaned =[]
  for word in words:
    if word not in stopwords:
      cleaned.append(word)
  return " ".join(cleaned)

In [23]:
df['text']=df['text'].apply(remove)

In [24]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [25]:
df.head(

)

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['text'],df['emotion'],test_size=0.20,random_state=42)

In [28]:
X_test.value_counts()

text
feel agitated                                                                                                                     2
feel sincere                                                                                                                      2
feel dirty                                                                                                                        2
feel dumb                                                                                                                         2
feel bad                                                                                                                          2
                                                                                                                                 ..
felt bit bad killing always feels like chore simply distracted exploration                                                        1
almost feel greedy rd child many people know working hard                                                                         1
think easy feel afraid one considers nuclear weapons weather protests riots police reactions governments responses laws passed    1
want feel left faithful reader love                                                                                               1
evening brilliant night fantastic run feeling jolly darn good                                                                     1
Name: count, Length: 3192, dtype: int64

In [31]:
df.shape

(16000, 2)

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [40]:
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 116049 stored elements and shape (12800, 13359)>

In [41]:
X_test_bow = bow_vectorizer.transform(X_test)

In [42]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [43]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [44]:
pred_nb = nb_model.predict(X_test_bow)

In [45]:
print(accuracy_score(y_test,pred_nb))

0.7678125

In [46]:
tfidfv = TfidfVectorizer()

In [47]:
X_train_tf = tfidfv.fit_transform(X_train)
X_test_tf = tfidfv.transform(X_test)

nb2_model = MultinomialNB()
nb2_model.fit(X_train_tf,y_train)

MultinomialNB()

In [48]:
pred_nb2 = nb2_model.predict(X_test_tf)
print(accuracy_score(y_test,pred_nb2))

0.6609375

In [49]:
from sklearn.linear_model import LogisticRegression
logis_model = LogisticRegression(max_iter=1000)
logis_model.fit(X_train_tf,y_train)
pred_logis = logis_model.predict(X_test_tf)
print(accuracy_score(y_test,pred_logis))

0.8615625

In [50]:
logis_model = LogisticRegression(max_iter=1000)
logis_model.fit(X_train_bow,y_train)
pred_logis = logis_model.predict(X_test_bow)
print(accuracy_score(y_test,pred_logis))

0.88875

In [51]:
import pickle

# Save the logis_model to a file
with open('logistic_regression_model.pkl', 'wb') as file:
    pickle.dump(logis_model, file)

print('Logistic Regression model saved successfully as logistic_regression_model.pkl')

Logistic Regression model saved successfully as logistic_regression_model.pkl